[build]
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
